import { Inter } from 'next/font/google';
import './globals.css';
import NavMenu from './components/NavMenu';
import React from 'react';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col h-screen">
          <NavMenu />
          <main className="flex-1 px-20 py-2 flex flex-col justify-center">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
