import { Inter } from 'next/font/google';
import './globals.css';
import { getServerSession } from 'next-auth';
import SessionProvider from './components/SessionProvider';
import NavMenu from './components/NavMenu';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <div className="flex flex-col h-screen">
            <NavMenu />
            <main className="flex-1 px-20 py-2 flex flex-col justify-center">
              {children}
            </main>
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}
